[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; LittleFS for web UI and config persistence
board_build.filesystem = littlefs

lib_deps =
    gin66/FastAccelStepper@^0.30.12
    madhephaestus/ESP32Servo@^3.0.5
    miguelbalboa/MFRC522@^1.4.11
    me-no-dev/ESPAsyncWebServer@^1.2.7
    me-no-dev/AsyncTCP@^1.1.4
    adafruit/Adafruit NeoPixel@^1.12.3
    bblanchon/ArduinoJson@^7.2.0

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_ASYNC_TCP_RUNNING_CORE=1

monitor_filters = esp32_exception_decoder
